In [1]:
#assignment -4   13/07/2026
import numpy as np


In [2]:
# Question 1
arr1 = np.arange(1, 13)
print("Q1 - 3x4 Matrix:\n", arr1.reshape(3, 4))

Q1 - 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# Question 2
arr2 = np.arange(1, 17)
print("\nQ2 - 4x4 Matrix:\n", arr2.reshape(4, 4))


Q2 - 4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
# Question 3
arr3 = np.arange(1, 25)
print("\nQ3 - 2x3x4 3D Array:\n", arr3.reshape(2, 3, 4))


Q3 - 2x3x4 3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
# Question 4
arr4 = np.arange(1, 19)
print("\nQ4 - 3x6 Matrix:\n", arr4.reshape(3, 6))


Q4 - 3x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [6]:
#Question 5
arr5 = np.arange(1, 21)
print("\nQ5 - Reshape with -1:\n", arr5.reshape(4, -1))


Q5 - Reshape with -1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
# Question 6
arr6 = np.arange(1, 13).reshape(3, 4)
print("\nQ6 - Reshaped to 2x6:\n", arr6.reshape(2, 6))


Q6 - Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
# Question 7
arr7 = np.arange(1, 13).reshape(2, 3, 2)
print("\nQ7 - 3D converted back to 1D:\n", arr7.reshape(-1))


Q7 - 3D converted back to 1D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# Question 8
arr8 = np.arange(1, 10).reshape(3, 3)
print("Q8 - Flattened array:\n", arr8.flatten())

Q8 - Flattened array:
 [1 2 3 4 5 6 7 8 9]


In [11]:
# Question 9
arr9 = np.arange(1, 9).reshape(4, 2)
print("\nQ9 - Ravel array:\n", arr9.ravel())


Q9 - Ravel array:
 [1 2 3 4 5 6 7 8]


In [14]:
# Question 10
arr10 = np.arange(1, 9).reshape(2, 4)
print("\nQ10 - Transpose using transpose():", np.transpose(arr10))


Q10 - Transpose using transpose(): [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [15]:
# Question 12
arr12 = np.array([10, 20, 30])
print("\nQ12 - Resized to 3x3:\n", np.resize(arr12, (3, 3)))


Q12 - Resized to 3x3:
 [[10 20 30]
 [10 20 30]
 [10 20 30]]


In [18]:
# Question 13
arr13 = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr13.flatten()
flat_arr[0] = 99
print("\nQ13 - Original Matrix:\n", arr13)
print(" Modified Array:", flat_arr)


Q13 - Original Matrix:
 [[1 2 3]
 [4 5 6]]
 Modified Array: [99  2  3  4  5  6]


In [20]:
# Question 14
arr14 = np.array([[1, 2, 3], [4, 5, 6]])
rav_arr = arr14.ravel()
rav_arr[0] = 99
print("\nQ14 - Original Matrix:\n", arr14)
print(" Modified Array:", rav_arr)


Q14 - Original Matrix:
 [[99  2  3]
 [ 4  5  6]]
 Modified Array: [99  2  3  4  5  6]


In [21]:
# Question 15
a1 = np.array([10, 20, 30])
a2 = np.array([40, 50, 60])
print("Q15 - Concatenated Array:", np.concatenate((a1, a2)))

Q15 - Concatenated Array: [10 20 30 40 50 60]


In [22]:
# Question 16
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("\nQ16 - Column-wise Merge (hstack):\n", np.hstack((m1, m2)))


Q16 - Column-wise Merge (hstack):
 [[1 2 5 6]
 [3 4 7 8]]


In [24]:
# Question 17
print("Q17 - Row-wise Merge (vstack):\n", np.vstack((m1, m2)))

Q17 - Row-wise Merge (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
# Question 18
arr18 = np.arange(1, 13)
print("Q18 - Split 1D into 4 equal parts:\n", np.split(arr18, 4))

Q18 - Split 1D into 4 equal parts:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [29]:
# Question 19
arr19 = np.arange(1, 9).reshape(4, 2)
print("Q19 - Split 4x2 matrix into 2 parts:\n", np.split(arr19, 2))

Q19 - Split 4x2 matrix into 2 parts:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [30]:
# Question 20
c1 = np.array([1, 2])
c2 = np.array([3, 4])
c3 = np.array([5, 6])
print("Q20 - Merge 3 arrays:\n", np.concatenate((c1, c2, c3)))

Q20 - Merge 3 arrays:
 [1 2 3 4 5 6]


In [31]:
# Question 21
salaries = np.array([25000, 30000, 35000, 40000, 45000])
print("Q21 - Salaries with ₹5000 Bonus:\n", salaries + 5000)

Q21 - Salaries with ₹5000 Bonus:
 [30000 35000 40000 45000 50000]


In [32]:
marks = np.array([[70, 80, 90], [60, 75, 85]])
grace = np.array([5, 5, 10])
print("\nQ22 - Updated Marks:\n", marks + grace)


Q22 - Updated Marks:
 [[ 75  85 100]
 [ 65  80  95]]


In [34]:
# Question 23
arr23 = np.array([10, 20, 30, 40])
arr23_copy = arr23.copy()
arr23_copy[0] = 99
print("\nQ23 - Original Array:", arr23)
print("  Copied Array:", arr23_copy)


Q23 - Original Array: [10 20 30 40]
  Copied Array: [99 20 30 40]


In [36]:
# Question 24
arr24 = np.array([100, 200, 300, 400])
arr24_view = arr24.view()
arr24_view[0] = 999
print("\nQ24 - Original Array (Affected):", arr24)
print("View Array:", arr24_view)


Q24 - Original Array (Affected): [999 200 300 400]
View Array: [999 200 300 400]


In [41]:
#Mini Project
emp_salary = np.array([[25000, 30000, 35000],
                       [40000, 45000, 50000]])

print("1. Original Matrix:")
print(emp_salary)

print("\n2. Reshaped into 3x2 :")
reshaped_salary = emp_salary.reshape(3, 2)
print(reshaped_salary)

print("\n3. Flattened Reshaped Matrix:")
flattened_salary = reshaped_salary.flatten()
print(flattened_salary)

print("\n4. Transpose of Original Matrix :")
print(np.transpose(emp_salary))

print("\n5. Increased Salary by ₹2000 (Broadcasting):")
updated_salary = emp_salary + 2000
print(updated_salary)

print("\n 6. Copy :")
salary_copy = emp_salary.copy()
salary_copy[0, 0] = 99999
print("Original Matrix (Unchanged):\n", emp_salary)
print("Copied Matrix (Modified):\n", salary_copy)

print("\n 7. View :")
salary_view = emp_salary.view()
salary_view[0, 0] = 11111
print("Original Matrix:\n", emp_salary)
print("View Matrix:\n", salary_view)

1. Original Matrix:
[[25000 30000 35000]
 [40000 45000 50000]]

2. Reshaped into 3x2 :
[[25000 30000]
 [35000 40000]
 [45000 50000]]

3. Flattened Reshaped Matrix:
[25000 30000 35000 40000 45000 50000]

4. Transpose of Original Matrix :
[[25000 40000]
 [30000 45000]
 [35000 50000]]

5. Increased Salary by ₹2000 (Broadcasting):
[[27000 32000 37000]
 [42000 47000 52000]]

 6. Copy :
Original Matrix (Unchanged):
 [[25000 30000 35000]
 [40000 45000 50000]]
Copied Matrix (Modified):
 [[99999 30000 35000]
 [40000 45000 50000]]

 7. View :
Original Matrix:
 [[11111 30000 35000]
 [40000 45000 50000]]
View Matrix:
 [[11111 30000 35000]
 [40000 45000 50000]]
