In [1]:
#03/07/2026
import numpy as np
print(" Q1 :")
arr_q1 = np.array([10, 20, 30, 40, 50])
print("First element:", arr_q1[0])

 Q1 :
First element: 10


In [2]:
print(" Q2:")
arr_q2 = np.array([5, 10, 15, 20, 25, 30])
print("Last element (negative indexing):", arr_q2[-1])

 Q2:
Last element (negative indexing): 30


In [3]:
print(" Q 3 :")
arr_q3 = np.array([100, 200, 300, 400, 500])
print("Third element:", arr_q3[2])

 Q 3 :
Third element: 300


In [4]:
matrix_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(matrix_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
print(" Q 4:")
print("Element 50:", matrix_2d[1, 1])

 Q 4:
Element 50: 50


In [6]:
print("Q 5:")
print("Element 90:", matrix_2d[2, 2])

Q 5:
Element 90: 90


In [8]:
matrix_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(matrix_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print("Q6:")
print("Element 6:", matrix_3d[1, 0, 1])

Q6:
Element 6: 6


In [10]:
print(" Q 7:")
print("Element 3:", matrix_3d[0, 1, 0])

 Q 7:
Element 3: 3


In [11]:
array= np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(array)

[10 20 30 40 50 60 70 80]


In [12]:
print("Q8:")
print("First four elements:", array[:4])

Q8:
First four elements: [10 20 30 40]


In [13]:
print("Q 9:")
print("Elements from 30 to 60:", array[2:6])

Q 9:
Elements from 30 to 60: [30 40 50 60]


In [14]:
print("Q10:")
print("Elements from 50 to end:", array[4:])

Q10:
Elements from 50 to end: [50 60 70 80]


In [15]:
print("Question 11 :")
print("Every second element:", array[::2])

Question 11 :
Every second element: [10 30 50 70]


In [16]:
print("Question 12:")
print("Last three elements:", array[-3:])

Question 12:
Last three elements: [60 70 80]


In [17]:
print("Question 13:")
print("First row:\n", matrix_2d[0])

Question 13:
First row:
 [10 20 30]


In [18]:
print(" Question 14:")
print("Last row:\n", matrix_2d[-1])

 Question 14:
Last row:
 [70 80 90]


In [19]:
print(" Question 15:")
print("Second column:\n", matrix_2d[:, 1])

 Question 15:
Second column:
 [20 50 80]


In [20]:
print("Question 16 :")
print("Third column:\n", matrix_2d[:, 2])

Question 16 :
Third column:
 [30 60 90]


In [21]:
print("Question 17:")
print("First two rows:\n", matrix_2d[:2])

Question 17:
First two rows:
 [[10 20 30]
 [40 50 60]]


In [22]:
print("Question 18:")
print("First two columns:\n", matrix_2d[:, :2])

Question 18:
First two columns:
 [[10 20]
 [40 50]
 [70 80]]


In [24]:
print("Question 19:")
print("matrix:\n", matrix_2d[:2, :2])

Question 19:
matrix:
 [[10 20]
 [40 50]]


In [26]:
print(" Question 20 :")
arr_q20 = np.array([10, 20, 30, 40, 50])
print("Array created:\n", arr_q20)

 Question 20 :
Array created:
 [10 20 30 40 50]
