In [2]:
#08/07/2026
import numpy as np
arr_1d = np.arange(1, 21)
print(f" 1D Array:\n{arr_1d}")

 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
print(" Q1: Display the first element:")
print("First element:", arr_1d[0])

 Q1: Display the first element:
First element: 1


In [5]:
print("Q2: Display the last element using negative indexing:")
print("Last element:", arr_1d[-1])

Q2: Display the last element using negative indexing:
Last element: 20


In [6]:
print("Q3: Display the third element of an array")
print("Third element (index 2):", arr_1d[2])

Q3: Display the third element of an array
Third element (index 2): 3


In [7]:
print("Q4: Display the last five elements using slicing:")
print("Last five elements:", arr_1d[-5:])

Q4: Display the last five elements using slicing:
Last five elements: [16 17 18 19 20]


In [8]:
print(" Q5: Display elements from index 3 to 8:")
print("Elements from index 3 to 8:", arr_1d[3:8])

 Q5: Display elements from index 3 to 8:
Elements from index 3 to 8: [4 5 6 7 8]


In [10]:
matrix_4x4 = np.arange(1, 17).reshape(4, 4)
print(f"Base 4x4 Matrix:\n{matrix_4x4}")

Base 4x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
print("Q6: Display the first row:")
print(matrix_4x4[0, :])

Q6: Display the first row:
[1 2 3 4]


In [12]:
print("Q7: Display the last row of the matrix:")
print(matrix_4x4[-1, :])

Q7: Display the last row of the matrix:
[13 14 15 16]


In [13]:
print(" Q8: Display the first column:")
print(matrix_4x4[:, 0])

 Q8: Display the first column:
[ 1  5  9 13]


In [14]:
print("Q9: Display the last column :")
print(matrix_4x4[:, -1])

Q9: Display the last column :
[ 4  8 12 16]


In [15]:
print("Q10: Display the middle two rows:")
print(matrix_4x4[1:3, :])

Q10: Display the middle two rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print("Q11: Display the middle two columns :")
print(matrix_4x4[:, 1:3])

Q11: Display the middle two columns :
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [17]:
print("Q12: Display the first 2 x 2 sub-matrix:")
print(matrix_4x4[0:2, 0:2])

Q12: Display the first 2 x 2 sub-matrix:
[[1 2]
 [5 6]]


In [18]:
print("Q13: Display the last 2 x 2 sub-matrix:")
print(matrix_4x4[2:4, 2:4])

Q13: Display the last 2 x 2 sub-matrix:
[[11 12]
 [15 16]]


In [20]:
arr_3d = np.arange(1, 19).reshape(2, 3, 3)
print(f" 3D Array:\n{arr_3d}")

 3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [21]:
print(" Q14: Create a 3D array and display the first matrix:")
print(arr_3d[0, :, :])

 Q14: Create a 3D array and display the first matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print("Q15: Display the second matrix of a 3D array :")
print(arr_3d[1, :, :])

Q15: Display the second matrix of a 3D array :
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [23]:
print("Q16: Display a specific element from a 3D array :")
# Accesses the 2nd matrix, 3rd row, 2nd column (number 17)
print("Element at index [1, 2, 1]:", arr_3d[1, 2, 1])

Q16: Display a specific element from a 3D array :
Element at index [1, 2, 1]: 17


In [25]:
arr_bool = np.arange(1, 21)
print(f"Base Array for Boolean Indexing:\n{arr_bool}")

Base Array for Boolean Indexing:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [27]:
print("Q17: Display only even numbers using Boolean Indexing:")
print(arr_bool[arr_bool % 2 == 0])

Q17: Display only even numbers using Boolean Indexing:
[ 2  4  6  8 10 12 14 16 18 20]


In [26]:
print("Q18: Display only odd numbers using Boolean Indexing:")
print(arr_bool[arr_bool % 2 != 0])

Q18: Display only odd numbers using Boolean Indexing:
[ 1  3  5  7  9 11 13 15 17 19]


In [28]:
print("Q19: Display numbers greater than 10 using Boolean Indexing:")
print(arr_bool[arr_bool > 10])

Q19: Display numbers greater than 10 using Boolean Indexing:
[11 12 13 14 15 16 17 18 19 20]


In [29]:
print(" Q20: Display numbers less than 15 using Boolean Indexing :")
print(arr_bool[arr_bool < 15])

 Q20: Display numbers less than 15 using Boolean Indexing :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
print("Q21: Use Fancy Indexing to display elements at index positions 0, 2, 4, 6:")
indices_1 = [0, 2, 4, 6]
print(arr_1d[indices_1])

Q21: Use Fancy Indexing to display elements at index positions 0, 2, 4, 6:
[1 3 5 7]


In [31]:
print("Q22: Use Fancy Indexing to display the first and last elements:")
indices_2 = [0, -1]
print(arr_1d[indices_2])

Q22: Use Fancy Indexing to display the first and last elements:
[ 1 20]


In [32]:
print("Q23: Create a 5 x 5 matrix:")
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print(f" 5x5 Matrix:\n{matrix_5x5}")
print("First row:", matrix_5x5[0, :])
print("Last row:", matrix_5x5[-1, :])
print("First column:", matrix_5x5[:, 0])
print("Last column:", matrix_5x5[:, -1])

Q23: Create a 5 x 5 matrix:
 5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last row: [21 22 23 24 25]
First column: [ 1  6 11 16 21]
Last column: [ 5 10 15 20 25]


In [33]:
print("Q24: Create a 4 x 5 matrix and display only the first 3 columns:")
matrix_4x5 = np.arange(1, 21).reshape(4, 5)
print(f"Base 4x5 Matrix:\n{matrix_4x5}")
print("First 3 columns:\n", matrix_4x5[:, 0:3])

Q24: Create a 4 x 5 matrix and display only the first 3 columns:
Base 4x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
First 3 columns:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
