In [1]:
#07/07/2026
import numpy as np

# Question 1
print("Q1: Import the NumPy library")
print("NumPy library imported as 'np'.\n")

Q1: Import the NumPy library
NumPy library imported as 'np'.



In [2]:
print(" Q2: Create a 1D NumPy array containing numbers from 1 to 10:")
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr_1d)

 Q2: Create a 1D NumPy array containing numbers from 1 to 10:
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Q3: Create a 2D array of size 3 x 3 :")
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

Q3: Create a 2D array of size 3 x 3 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(": Create a 3D array of size 2 x 2 x 3 ---")
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(arr_3d)

: Create a 3D array of size 2 x 2 x 3 ---
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
print(" Q5: Display the number of dimensions (ndim) of a 2D array:")
print("Dimensions:", arr_2d.ndim)

 Q5: Display the number of dimensions (ndim) of a 2D array:
Dimensions: 2


In [7]:
print("Q6: Display the shape of a 3D array :")
print("Shape:", arr_3d.shape)

Q6: Display the shape of a 3D array :
Shape: (2, 2, 3)


In [8]:
print("Q7: Display the total number of elements using size:")
print("Total number of elements:", arr_3d.size)

Q7: Display the total number of elements using size:
Total number of elements: 12


In [9]:
print(" Q8: Display the data type (dtype) of an array :")
print("Data type:", arr_1d.dtype)

 Q8: Display the data type (dtype) of an array :
Data type: int64


In [10]:
print(" Q9: Create a 5 x 5 array filled with zeros ---")
zeros_arr = np.zeros((5, 5))
print(zeros_arr)

 Q9: Create a 5 x 5 array filled with zeros ---
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
print("Q10: Create a 4 x 4 array filled with ones :")
ones_arr = np.ones((4, 4))
print(ones_arr)

Q10: Create a 4 x 4 array filled with ones :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
print(" Q11: Create a 3 x 3 array filled with the value 100:")
full_arr = np.full((3, 3), 100)
print(full_arr)

 Q11: Create a 3 x 3 array filled with the value 100:
[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [13]:
print("Q12: Create a 5 x 5 Identity Matrix :")
identity_5 = np.eye(5)
print(identity_5)

Q12: Create a 5 x 5 Identity Matrix :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
print(" Q13: Create an array using arange() from 10 to 50 :")
range_arr = np.arange(10, 51)
print(range_arr)

 Q13: Create an array using arange() from 10 to 50 :
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [15]:
print(" Q14: Create an array using arange() with a step size of 5 :")
step_arr = np.arange(0, 51, 5)
print(step_arr)

 Q14: Create an array using arange() with a step size of 5 :
[ 0  5 10 15 20 25 30 35 40 45 50]


In [16]:
print(" Q15: Create an array using linspace() from 1 to 100 with 10 values:")
lin_arr1 = np.linspace(1, 100, 10)
print(lin_arr1)

 Q15: Create an array using linspace() from 1 to 100 with 10 values:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [17]:
print(" Q16: Create an array containing decimal values using linspace():")
lin_arr2 = np.linspace(0.0, 1.0, 5)
print(lin_arr2)

 Q16: Create an array containing decimal values using linspace():
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print("Q17: Create a Student Marks array containing marks of 10 students:")
student_marks = np.array([85, 92, 78, 65, 89, 94, 72, 81, 90, 88])
print(student_marks)

In [19]:
print("Q18: Display the shape, size, ndim, and dtype of the Student Marks array:")
student_marks = np.array([85, 92, 78, 65, 89, 94, 72, 81, 90, 88])
print("Shape:", student_marks.shape)
print("Size:", student_marks.size)
print("Dimensions:", student_marks.ndim)
print("Data Type:", student_marks.dtype)

Q18: Display the shape, size, ndim, and dtype of the Student Marks array:
Shape: (10,)
Size: 10
Dimensions: 1
Data Type: int64


In [20]:
print("Q19: Create a 2 x 5 array using array():")
arr_2x5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_2x5)

Q19: Create a 2 x 5 array using array():
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
print("Q20: Create a 3 x 4 array using nested lists:")
nested_list = [[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]
arr_from_nested = np.array(nested_list)
print(arr_from_nested)

Q20: Create a 3 x 4 array using nested lists:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [ ]:
print("Q21: Create an array of floating-point numbers:")
float_arr = np.array([1.5, 2.75, 3.0, 4.2], dtype=float)
print(float_arr)
print("Dtype:", float_arr.dtype)

In [22]:
print("Q22: Create an array of string values:")
string_arr = np.array(['Python', 'NumPy', 'Pandas', 'SciPy'])
print(string_arr)
print("Dtype:", string_arr.dtype)

Q22: Create an array of string values:
['Python' 'NumPy' 'Pandas' 'SciPy']
Dtype: <U6


In [23]:
print("Q23: Create an array of Boolean values:")
bool_arr = np.array([True, False, True, True, False])
print(bool_arr)
print("Dtype:", bool_arr.dtype)

Q23: Create an array of Boolean values:
[ True False  True  True False]
Dtype: bool


In [24]:
print(" Q24: Create a 6 x 6 matrix of zeros :")
zeros_6x6 = np.zeros((6, 6))
print(zeros_6x6)

 Q24: Create a 6 x 6 matrix of zeros :
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
print("Q25: Create a 10 x 10 Identity Matrix:")
identity_10 = np.eye(10)
print(identity_10)

Q25: Create a 10 x 10 Identity Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
