In [2]:
import numpy as np
#Q1
print(" Q1: Student Marks Array :")
marks = np.array([78, 85, 90, 67, 88, 92, 75, 81, 69, 95])
print("Complete array:", marks)
print("Data type:", marks.dtype)
print("Total number of elements:", marks.size)

 Q1: Student Marks Array :
Complete array: [78 85 90 67 88 92 75 81 69 95]
Data type: int64
Total number of elements: 10


In [3]:
print("Q2: Employee IDs:")
employee_ids = np.array([101, 102, 103, 104, 105, 106])
print("Array:", employee_ids)
print("Number of dimensions:", employee_ids.ndim)
print("Shape:", employee_ids.shape)

Q2: Employee IDs:
Array: [101 102 103 104 105 106]
Number of dimensions: 1
Shape: (6,)


In [4]:
print("Q3: College Students Data (2D Array):")
students_data = np.array([
    [78, 82, 90],
    [65, 70, 88],
    [91, 86, 79]
])
print("Complete array:\n", students_data)
print("Shape:", students_data.shape)
print("Size (total elements):", students_data.size)
print("Data type:", students_data.dtype)

Q3: College Students Data (2D Array):
Complete array:
 [[78 82 90]
 [65 70 88]
 [91 86 79]]
Shape: (3, 3)
Size (total elements): 9
Data type: int64


In [6]:
print(" Q4: Zero Matrix:")
zeros_matrix = np.zeros((5, 5))
print("5x5 Zero Matrix:\n", zeros_matrix)

 Q4: Zero Matrix:
5x5 Zero Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
print("Q5: Ones Matrix:")
ones_matrix = np.ones((4, 6))
print("4x6 Ones Matrix:\n", ones_matrix)

Q5: Ones Matrix:
4x6 Ones Matrix:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
print(" Q 6: Identity Matrix:")
identity_matrix = np.eye(6)
print("6x6 Identity Matrix:\n", identity_matrix)

 Q 6: Identity Matrix:
6x6 Identity Matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
print("Q7: Full Matrix:")
full_matrix = np.full((4, 4), 25)
print("4x4 Matrix filled with 25:\n", full_matrix)

Q7: Full Matrix:
4x4 Matrix filled with 25:
 [[25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]]


In [12]:
print("Q8: arange():")
array1 = np.arange(1, 11)
array2 = np.arange(10, 101, 10)
print("Array 1 (1 to 10):", array1)
print("Array 2 (10 to 100):", array2)

Q8: arange():
Array 1 (1 to 10): [ 1  2  3  4  5  6  7  8  9 10]
Array 2 (10 to 100): [ 10  20  30  40  50  60  70  80  90 100]


In [13]:
print(" Q 9: linspace():")
array = np.linspace(0, 100, 8)
print("linspace():\n",array)

 Q 9: linspace():
linspace():
 [  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [14]:
print("Q10: Complete Array Properties:")
array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Array:\n",array)
print("Number of Dimensions (ndim):",array.ndim)
print("Shape (shape):",array.shape)
print("Size (size):",array.size)
print("Data Type (dtype):",array.dtype)

Q10: Complete Array Properties:
Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Number of Dimensions (ndim): 2
Shape (shape): (3, 3)
Size (size): 9
Data Type (dtype): int64
